#ifndef __MY_CONSTANT_H__
#define __MY_CONSTANT_H__

typedef enum {
	MY_PROTOTYPE_STYLE_STRAIGHT_LINE,
	MY_PROTOTYPE_STYLE_SPLINE,
	MY_PROTOTYPE_STYLE_SPLINE_CYC,
	MY_PROTOTYPE_STYLE_SPLINE_OVERLAP,
	MY_PROTOTYPE_STYLE_BEZIER,
	MY_PROTOTYPE_STYLE_BEZIER_JM,
	MY_PROTOTYPE_STYLE_BEZIER_SIN,
	MY_PROTOTYPE_STYLE_PICTURE
} MyPrototypeStyle;


typedef enum {
	MY_PROTOTYPE_CATEGORY_STANDARD,
	MY_PROTOTYPE_CATEGORY_FAST,
} MyPrototypeCategory;

typedef enum {
	MY_MOUSE_LEFT,
	MY_MOUSE_MIDDLE,
	MY_MOUSE_RIGHT,
} MyMouse;

#endif /*__MY_CONSTANT_H__*/